fix: adjusting gitlab atlantis image
konstructio/kubefirst-docs pull request #215
Opened 2023-04-04 03:05 UTC by johndietz

2023-04-04 03:07 UTC, jarededwards approved these changes

2023-04-04 03:17 UTC, echoboomer approved these changes

2023-04-04 13:26 UTC, fharper requested changes
This PR ovwerwrite the Atlantis screenshot for GitHub, so if we merge, it will be GitLab screenshots everywhere in the docs.

2023-04-04 19:44 UTC, closed without merging

2023-04-05 14:23 UTC, fharper commented
Not sure why this PR was closed, and not fixed as the GitLab image need to be updated. I'll create a new PR to do that.